module.exports = {
	SPIDER: {
		"INITIALIZED": "SPIDER:INITIALIZED",
		"CRAWLING": "SPIDER:CRAWLING",
		"FINISHED": "SPIDER:FINISHED",
		"ERRORED": "SPIDER:ERRORED"
	},

	ANT: {
		"INITIALIZED": "ANT:INITIALIZED",
		"CRAWLING": "ANT:CRAWLING",
		"FINISHED": "ANT:FINISHED"
	}
}